name: GitHub Actions For StackrModule
run-name: ${{ github.actor }} is running the workflow to push the latest code into the Terraform Module Registry
on:
  push:
    branches:
      - main
jobs:
  StackrModule-Build-Sphinx-Docs:
    name: Build Sphinx documentation
    runs-on: ubuntu-latest
    steps:
      - name: Print context info
        run: | 
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: # optional
          # Path to the go.mod or go.work file.
          go-version-file: test/resourceGroup
          # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
          check-latest: true
          # Used to specify the path to a dependency file - go.sum
          cache-dependency-path: test/resourceGroup
      - name: Do the Sphinx Build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - name: Print job status
        run: |
          echo "This job's status is ${{ job.status }}."
