name: GitHub Actions For StackrModule
run-name: ${{ github.actor }} is running the workflow to push the latest code into the Terraform Module Registry
on:
  push:
    branches:
      - main
jobs:
  StackrModule-Build-Cucumber-And-Docs:
    name: Build Cucumber And Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Print context info
        run: | 
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository post checkout
        run: |
          ls -R ${{ github.workspace }}
      - name: Log me into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
      - name: Init and Tidy
        run: |
          cd test/resourceGroup
          go version
          # go mod init github.com/tunix78/stackrModule
          # go mod tidy
      - name: Test
        run: |
          cd test/resourceGroup
          mkdir results
          go test -v --godog.random --godog.format=cucumber:results/cucumber.json
      - name: Do the Sphinx Build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
      - name: List files in the repository post build
        run: |
          ls -R ${{ github.workspace }}
      - name: Print job status
        run: |
          echo "This job's status is ${{ job.status }}."
