name: GitHub Actions For StackrModule
run-name: ${{ github.actor }} is running the workflow to push the latest code into the Terraform Module Registry
on:
  push:
    branches:
      - main
jobs:
  StackrModule-Build-Cucumber-And-Docs:
    name: Build Cucumber And Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Print context info
        run: | 
          echo "The job was automatically triggered by a ${{ github.event_name }} event."
          echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "The ${{ github.repository }} repository has been cloned to the runner."
          echo "The workflow is now ready to test your code on the runner."
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          repository: tunix78/stackrModule
          path: stackrModule
      - name: Checkout stackrOpa
        uses: actions/checkout@v3
        with:
          repository: tunix78/stackrOpa
          token: ${{ secrets.STACKR_OPA_ACCESS_PAT }}
          path: stackrOpa
      - name: Checkout stackrTools
        uses: actions/checkout@v3
        with:
          repository: tunix78/stackrTools
          token: ${{ secrets.STACKR_TOOLS_ACCESS_PAT }}
          path: stackrTools
      - name: List files in the repository post checkout
        run: |
          ls -R ${{ github.workspace }}
      - name: Log me into Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
      - name: Init and Tidy
        run: |
          cd stackrModule/test/resourceGroup
          go version
          # go mod init github.com/tunix78/stackrModule
          # go mod tidy
      - name: Test
        run: |
          cd stackrModule/test/resourceGroup
          mkdir -p results
          go test -v --godog.random --godog.format=cucumber:results/cucumber.json
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: Install cucumber-html-reporter
        run: npm install cucumber-html-reporter --save-dev
      - name: Create html reports
        run: |
          cd stackrModule/test
          node index.js
      - name: Upload cucumber reports to data store and timestamp, version them
        run: |
          stackrModule/docs/_build/html
      - name: Do the Sphinx Build
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "stackrModule/docs/"
      - name: List files in the repository post build
        run: |
          ls -R ${{ github.workspace }}
      - name: Print job status
        run: |
          echo "This job's status is ${{ job.status }}."
